sudo: false
language: cpp
compiler: gcc
branches:
  only:
    - master
    - develop
    - /^release\/.*/
    - /^hotfix\/.*/

addons:
  apt:
    sources:
      - boost-latest
    packages:
      - libboost1.55-all-dev
      - libopencv-dev
      - libeigen3-dev
      - libflann-dev
      - lcov

before_install:
  - pip install --user cpp-coveralls
before_script:
  - export PATH=$PATH:/home/travis/src/DisCODe/build/inst/bin
  - export DISCODE_DCL_DIR=/home/travis/src/DCL/
  - cd ~/build/qiubix/SampleGenerators
  - ./install_discode.sh
script: cmake -DCMAKE_BUILD_TYPE=Debug . && make && make test
after_success:
  - coveralls --exclude ext --gcov-options '\-lp'
